# Generated by Django 2.2.12 on 2020-04-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foowipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
